### PR TITLE
Fix/time logic

### PR DESCRIPTION
**Pull request by leizmonk**

### CODE REVIEW

**Comment by leizmonk** [comment]
sry this was meant to be based of a fork of this repo, not for this parent repo

**Comment by Ahmadposten** [comment]
@leizmonk no problem man .. i encourage you to submit pull requests to this one too

**Comment by leizmonk** [comment]
@Ahmadposten oh cool! i paired your lib up with https://www.npmjs.com/package/slackbots to provide some more customization. Two things I worked on:

1. Create an option that only runs the reminder bot during specified work hours and days. Right now, it's configured directly in the index.js but I can extract those to env vars.
2. Create a `reminder-fetch` command that when received by a linked `slackbots` bot will trigger a reminder to the user that sent the command. 

If either of these sound interesting to you, I can create a couple PRs with those changes and submit.

**Comment by Ahmadposten** [comment]
@leizmonk both are very interesting specially the working hours issue .. I am also interested in making customizable messages .. let us team up

**Comment by leizmonk** [comment]
@Ahmadposten ok cool - when i get some time, i'll organize what i have into PRs and submit. `slackbots` is super easy to set up also. Aside from manual reminders, for now, I just have some easter eggs hah

**Pull request closed without merging**
